// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL3_8tuIagCnPMuM9o_PY7K4gvcohSZHY',
    appId: '1:65413130200:web:74211850873024b2c474ad',
    messagingSenderId: '65413130200',
    projectId: 'aplionepiece',
    authDomain: 'aplionepiece.firebaseapp.com',
    storageBucket: 'aplionepiece.firebasestorage.app',
    measurementId: 'G-BCFF6MCRGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYhErHSQm8TD4C0KYWJNpfIPmK6bKHeMI',
    appId: '1:65413130200:android:677b7171500ac4a3c474ad',
    messagingSenderId: '65413130200',
    projectId: 'aplionepiece',
    storageBucket: 'aplionepiece.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAL3_8tuIagCnPMuM9o_PY7K4gvcohSZHY',
    appId: '1:65413130200:web:8e1de5529ad8b8f3c474ad',
    messagingSenderId: '65413130200',
    projectId: 'aplionepiece',
    authDomain: 'aplionepiece.firebaseapp.com',
    storageBucket: 'aplionepiece.firebasestorage.app',
    measurementId: 'G-TE19GJFL7Q',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw7ft1UX-OZAw8B8qE_Q4LKhSV88ZmTV0',
    appId: '1:65413130200:ios:a4d5efe9fcd8147fc474ad',
    messagingSenderId: '65413130200',
    projectId: 'aplionepiece',
    storageBucket: 'aplionepiece.firebasestorage.app',
    iosBundleId: 'com.example.onepieceApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw7ft1UX-OZAw8B8qE_Q4LKhSV88ZmTV0',
    appId: '1:65413130200:ios:a4d5efe9fcd8147fc474ad',
    messagingSenderId: '65413130200',
    projectId: 'aplionepiece',
    storageBucket: 'aplionepiece.firebasestorage.app',
    iosBundleId: 'com.example.onepieceApp',
  );

}